version: 2

shared: &shared
  steps:
    - checkout
    - run: pip install tox tox-pyenv --user
    - run: tox -e $TOX_JOB
    - run: "[ $UPLOAD_COV ] && bash <(curl -s https://codecov.io/bash)"

jobs:
  py38:
    <<: *shared
    docker:
      - image: circleci/python:3.8
        environment:
          TOX_JOB: py38

  py37:
    <<: *shared
    docker:
      - image: circleci/python:3.7
        environment:
          TOX_JOB: py37

  py36:
    <<: *shared
    docker:
      - image: circleci/python:3.6
        environment:
          TOX_JOB: py36

  py35:
    <<: *shared
    docker:
      - image: circleci/python:3.5
        environment:
          TOX_JOB: py35

  lint:
    <<: *shared
    docker:
      - image: circleci/python:3.7
        environment:
          TOX_JOB: lint
